<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FooterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('footer_items')->insert([
            [
                'id' => 1,
                'name' => 'Guía de consulta y navegación de datos',
                'link' => null,
                'category' => 'Acerca del sitio',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-07-15 23:43:54',
            ],
            [
                'id' => 2,
                'name' => 'Secretaría de Salud',
                'link' => 'https://www.saludcapital.gov.co/Paginas2/Inicio.aspx',
                'category' => 'Aliados estratégicos',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 3,
                'name' => 'Cra. 32 No. 12 - 81, Bogotá-Colombia',
                'link' => null,
                'category' => 'Secretaría Distrital de Salud',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-07-18 01:47:51',
            ],
            [
                'id' => 4,
                'name' => 'Carrera 8 No. 10-55, Bogotá-Colombia',
                'link' => null,
                'category' => 'Alcaldía Mayor de Bogotá',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-07-18 01:47:55',
            ],
            [
                'id' => 5,
                'name' => 'Centro de relevo',
                'link' => 'https://www.centroderelevo.gov.co/632/w3-channel.html',
                'category' => 'Ayudas de accesibilidad',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-07-18 01:48:05',
            ],
            [
                'id' => 6,
                'name' => 'Políticas de privacidad',
                'link' => null,
                'category' => 'Acerca del sitio',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-07-15 22:50:57',
                'updated_at' => '2025-07-15 23:43:54',
            ],
            [
                'id' => 7,
                'name' => 'Elemento inactivo',
                'link' => null,
                'category' => 'Acerca del sitio',
                'order' => 3,
                'is_active' => 0,
                'created_at' => '2025-07-15 22:55:21',
                'updated_at' => '2025-07-15 23:43:54',
            ],
            [
                'id' => 8,
                'name' => 'Instituto Nacional de Vigilancia de Medicamento',
                'link' => 'https://www.invima.gov.co',
                'category' => 'Aliados estratégicos',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:44:25',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 9,
                'name' => 'Instituto Distrital de Gestión de Riesgos y Cambio Climático',
                'link' => 'https://www.idiger.gov.co',
                'category' => 'Aliados estratégicos',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:47:53',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 10,
                'name' => 'Instituto Nacional de Salud',
                'link' => 'https://www.ins.gov.co/Paginas/Inicio.aspx',
                'category' => 'Aliados estratégicos',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:48:09',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 11,
                'name' => 'Instituto de Hidrología, Meteorología y Estudios Ambientales',
                'link' => 'https://www.ideam.gov.co',
                'category' => 'Aliados estratégicos',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:49:34',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 12,
                'name' => 'Unidad Administrativa Especial de Servicios Públicos',
                'link' => 'https://www.uaesp.gov.co/noticias/enterate-te-contaremos-todo-lo-hacemos-bogota',
                'category' => 'Aliados estratégicos',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:49:51',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 13,
                'name' => 'Secretaría Distrital de Ambiente',
                'link' => 'https://www.ambientebogota.gov.co/es/inicio',
                'category' => 'Aliados estratégicos',
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:50:13',
                'updated_at' => '2025-07-16 00:27:49',
            ],
            [
                'id' => 14,
                'name' => 'saludambiental@saludcapital.gov.co',
                'link' => null,
                'category' => 'Secretaría Distrital de Salud',
                'order' => 10,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:50:42',
                'updated_at' => '2025-07-15 23:50:42',
            ],
            [
                'id' => 15,
                'name' => 'Lunes a viernes 8:00 a.m. a 5:00 p.m.',
                'link' => null,
                'category' => 'Secretaría Distrital de Salud',
                'order' => 11,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:50:56',
                'updated_at' => '2025-07-15 23:50:56',
            ],
            [
                'id' => 16,
                'name' => 'Bogotá - Colombia',
                'link' => null,
                'category' => 'Secretaría Distrital de Salud',
                'order' => 12,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:51:06',
                'updated_at' => '2025-07-15 23:51:06',
            ],
            [
                'id' => 17,
                'name' => '(601) 381 3000',
                'link' => null,
                'category' => 'Alcaldía Mayor de Bogotá',
                'order' => 13,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:51:30',
                'updated_at' => '2025-07-15 23:51:30',
            ],
            [
                'id' => 18,
                'name' => 'Lunes a viernes 8:00 a.m. a 7:00 p.m.',
                'link' => null,
                'category' => 'Alcaldía Mayor de Bogotá',
                'order' => 14,
                'is_active' => 1,
                'created_at' => '2025-07-15 23:51:42',
                'updated_at' => '2025-07-15 23:51:42',
            ],
            [
                'id' => 19,
                'name' => 'enlace de prueba',
                'link' => 'https://getbootstrap.com/docs/5.3/utilities/text/',
                'category' => 'Ayudas de accesibilidad',
                'order' => 15,
                'is_active' => 0,
                'created_at' => '2025-08-07 01:09:55',
                'updated_at' => '2025-08-07 01:10:14',
            ],
        ]);
    }
}
