<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NavSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'Redes de Hospitales',
                'route' => 'admin.home.network',
                'icon' => 'bi-reception-4',
                'module' => 'home',
                'category' => 'Navegación',
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 2,
                'name' => 'video principal',
                'route' => 'admin.home.video',
                'icon' => 'bi-play-btn-fill',
                'module' => 'home',
                'category' => 'Multimedia',
                'order' => 10,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 3,
                'name' => 'Noticias',
                'route' => 'admin.home.article',
                'icon' => 'bi-newspaper',
                'module' => 'home',
                'category' => null,
                'order' => 9,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 4,
                'name' => 'Indicadores de Clima',
                'route' => 'admin.home.insight',
                'icon' => 'bi-cloud-drizzle-fill',
                'module' => 'home',
                'category' => 'Indicadores',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 5,
                'name' => 'negocios saludables',
                'route' => 'admin.home.establishment',
                'icon' => 'bi-shop',
                'module' => 'home',
                'category' => 'Navegación',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 6,
                'name' => 'Paginas',
                'route' => 'admin.themes.page',
                'icon' => 'bi-file-earmark-text-fill',
                'module' => 'themes',
                'category' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 7,
                'name' => 'Banner Principal',
                'route' => 'admin.home.banner',
                'icon' => 'bi-easel',
                'module' => 'home',
                'category' => 'Galería',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 8,
                'name' => 'Calendario',
                'route' => 'admin.home.calendar',
                'icon' => 'bi-calendar-event',
                'module' => 'home',
                'category' => 'Indicadores',
                'order' => 11,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 9,
                'name' => 'Lineas de Interes',
                'route' => 'admin.home.line',
                'icon' => 'bi-bookmark',
                'module' => 'home',
                'category' => 'Navegación',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 11,
                'name' => 'Puntos de Recolección',
                'route' => 'admin.home.collection',
                'icon' => 'bi-recycle',
                'module' => 'home',
                'category' => 'Indicadores',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 12,
                'name' => 'Botones Destacados',
                'route' => 'admin.home.app',
                'icon' => 'bi-box',
                'module' => 'home',
                'category' => 'Multimedia',
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 13,
                'name' => 'Indicador Destacado',
                'route' => 'admin.home.featured',
                'icon' => 'bi-image-alt',
                'module' => 'home',
                'category' => 'Galería',
                'order' => 13,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 14,
                'name' => 'Eventos',
                'route' => 'admin.home.gallery',
                'icon' => 'bi-card-image',
                'module' => 'home',
                'category' => 'Galería',
                'order' => 12,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            // [
            //     'id' => 15,
            //     'name' => 'Pie de pagina',
            //     'route' => 'admin.home.footer',
            //     'icon' => 'bi bi-cursor',
            //     'module' => 'home',
            //     'category' => 'Navegación',
            //     'order' => 14,
            //     'is_active' => 1,
            //     'created_at' => '2025-06-21 00:00:00',
            //     'updated_at' => '2025-06-21 00:00:00',
            // ],
            [
                'id' => 17,
                'name' => 'Menús',
                'route' => 'admin.home.module',
                'icon' => 'bi bi-grid-fill',
                'module' => 'home',
                'category' => 'Navegación',
                'order' => 16,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 18,
                'name' => 'Navegación del Menú',
                'route' => 'admin.themes.navigation',
                'icon' => 'bi-list',
                'module' => 'themes',
                'category' => null,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 19,
                'name' => 'Banner del Menú',
                'route' => 'admin.themes.banner',
                'icon' => 'bi-image',
                'module' => 'themes',
                'category' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 20,
                'name' => 'Botones del Menú',
                'route' => 'admin.themes.buttons',
                'icon' => 'bi-menu-button-wide',
                'module' => 'themes',
                'category' => null,
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 21,
                'name' => 'Preguntas y respuestas',
                'route' => 'admin.themes.questions',
                'icon' => 'bi-question-circle',
                'module' => 'themes',
                'category' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 22,
                'name' => 'Política Distrital',
                'route' => 'admin.home.district',
                'icon' => 'bi bi-grid-fill',
                'module' => 'home',
                'category' => 'Navegación',
                'order' => 17,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 23,
                'name' => 'Página principal',
                'route' => 'admin.home.page',
                'icon' => 'bi-file-earmark-text-fill',
                'module' => 'home',
                'category' => 'Indicadores',
                'order' => 18,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 24,
                'name' => 'Muro social',
                'route' => 'admin.home.media',
                'icon' => 'bi-grid-3x3-gap-fill',
                'module' => 'home',
                'category' => 'Galería',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
            [
                'id' => 26,
                'name' => 'Página de registros',
                'route' => 'admin.themes.record',
                'icon' => 'bi-file-earmark-text-fill',
                'module' => 'themes',
                'category' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-21 00:00:00',
                'updated_at' => '2025-06-21 00:00:00',
            ],
        ]);
    }
}
